### ISSUE TITLE
👤 User reg/login/auth

### ISSUE THREAD

**Issue by KATT** [KATT/shop#24]
All apps needs login. Showcase how it's done.

**Comment by alan345** [comment]
Hi! nice job! yes, login/auth might be very useful. Need a commit for that?

**Comment by KATT** [comment]
@alan345 contributors are very welcome! Tell me - how can I help you help me? :)

If you wanna chat with me directly you can join the [Graph.cool Slack](https://slack.graph.cool/) - I'm "KATT" also there!
