### ISSUE TITLE
Maintaining shop repository.

### ISSUE THREAD

**Issue by wtrocki** [KATT/shop#825]
Hi

I stumbled upon this repository and it looks like it is no longer maintained. 
I'm one of the developers working on http://graphback.dev project that is giving similar capabilities to Prisma 1. Do you think it will be possible to update this awesome template to use Graphback that is maintained and supported open source solution? Would it be possible to maintain it (close PR's and issues etc.)?

**Comment by craicoverflow** [comment]
PR is available here. Client-side is not done until we can confirm this will be updated.

**Comment by wtrocki** [comment]
@craicoverflow Thanks for doing great job on this. Client-side got outdated so it will be much easier to recreate the client at some point. 


https://github.com/KATT/shop/pull/830

**Comment by wtrocki** [comment]
Bumping topic. CC @KATT

**Comment by KATT** [comment]
Hi! Sorry for missing this! I haven't seen the updates from github

Rather than changing the stack I'd prefer if you create a fork which I can link to at the top of my project

**Comment by KATT** [comment]
Make a fork and maintain that and I'll make sure to link it at the top with a notice saying _"this isn't maintained but check out this fork that has done a working version using Graphback instead of Prisma"_

**Comment by wtrocki** [comment]
@KATT Thank you for the response! That makes sense!
